import Head from "next/head";
import "./globals.css";
import { Outfit } from 'next/font/google'

const outfit = Outfit({subsets: ['latin']})

export const metadata = {
    title: "CashTrackr",
    description: "Generated by create next app",
    icons: {
        icon: '/favicon.png'
    }
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <Head>
                <link rel="ico" href="/favicon.png" type="image/png" />
            </Head>
            <body
                className={outfit.className}
            >
                {children}
            </body>
        </html>
    );
}
